// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmgxfxjoywmaxjprmeyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZ3hmeGpveXdtYXhqcHJtZXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzMzMzAsImV4cCI6MjA2Nzc0OTMzMH0.wZ72FpmPWo_9Hi4XxGuZgd3lz91Kqg72P8UAFRzg07Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});